language: rust

rust:
  - stable
  - nightly
  - 1.31.0  # Rust 2018

cache: cargo

env:
  global:
    - MGTEST=foo:$PATH

install:
  - >-
    curl -sSf https://build.travis-ci.org/files/rustup-init.sh | sh -s --
      --default-toolchain $TRAVIS_RUST_VERSION
      --profile minimal -y

script:
  - env
  - cargo build --verbose --all-features
  - cargo test --verbose --all-features
  - if [[ $TRAVIS_RUST_VERSION == "nightly" ]]; then cargo build --benches; fi
